server:
  port: 2000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  client.serviceUrl.defaultZone:  http://localhost:${server.port}/eureka/

logging:
  file: ./log/world-project-server.log

