server:
  port: 2020

spring:
  application:
    name: world-project-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native

security:
  user:
    password: oxbridge


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

logging:
  file: ./log/world-project-config.log

